# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/046a42ce-4c00-41c1-b611-d772d98adf6d";
    fsType = "btrfs";
    options = ["compress=zstd:1" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/046a42ce-4c00-41c1-b611-d772d98adf6d";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd:1" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/046a42ce-4c00-41c1-b611-d772d98adf6d";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd:1" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A30A-A09E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/911e1e33-8361-4cc3-aac8-58422aac2597";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
