# kwm — tiling window manager for river (dwm-inspired, Zig).
#
# Built with the same strategy nixpkgs uses for river 0.4.8:
#   zig_0_16 + zig.fetchDeps (fetches build.zig.zon git deps) and the
#   wayland/xkbcommon/pixman/fcft system libs link in build.zig.
# Protocol XMLs (river-*) are vendored in-repo and codegen'd by zig-wayland's
# scanner, so no wlroots check — kwm is just a river WM client.
#
# Runtime config is read from $XDG_CONFIG_HOME/kwm/config.zon (generated by
# modules/home/river/kwm.nix); the baked-in config.def.zon is only a fallback.
{
  lib,
  stdenv,
  fetchFromGitHub,
  pkg-config,
  wayland,
  wayland-scanner,
  wayland-protocols,
  libxkbcommon,
  pixman,
  fcft,
  zig_0_16,
}:
stdenv.mkDerivation (finalAttrs: {
  pname = "kwm";
  version = "0.3.0";

  src = fetchFromGitHub {
    owner = "kewuaa";
    repo = "kwm";
    rev = "3f966c9c79d4e31f58ea8d012129cda38f8115cc";
    hash = "sha256-k1NsihGCWnJVZXAi2y1F4QZ1GwHBijg6fW3mMq5eMgI=";
  };

  nativeBuildInputs = [
    pkg-config
    wayland-scanner
    zig_0_16
  ];

  buildInputs = [
    wayland
    wayland-scanner
    wayland-protocols
    libxkbcommon
    pixman
    fcft
  ];

  strictDeps = true;

  zigDeps = zig_0_16.fetchDeps {
    inherit (finalAttrs) src pname version;
    fetchAll = true;
    hash = "sha256-Lz/Wcy40rxN81n/mBj4YJVbyGOolHzSFZMs93T1h0oQ=";
  };

  postConfigure = ''
    ln -s ${finalAttrs.zigDeps} "$ZIG_GLOBAL_CACHE_DIR/p"
  '';

  meta = {
    description = "Tiling window manager for the river Wayland compositor (Zig, dwm-style, bar + window rules)";
    homepage = "https://github.com/kewuaa/kwm";
    license = lib.licenses.gpl3Only;
    mainProgram = "kwm";
    platforms = lib.platforms.linux;
  };
})